### ISSUE TITLE
有没有python的客户端呢？

### ISSUE THREAD

**Issue by ohyeah521** [mrluanma/shadowsocks-websocket-luvit#3]
我想要在路由器里面运行这个程序，不跟母亲openwrt平台不支持node语言，所以想要问问有没有python的客户端，如果有，需要如何配置？

**Comment by mrluanma** [comment]
没有。OpenWRT 建议用原生的 Shadowsocks，有各个版本的实现，我自己就在用 shadowsocks-libev。

**Comment by ohyeah521** [comment]
我的配置是这样的  node local.js -s  ssserver.com   -l 8888 -m rc4 -k password -r 80	
请问用  shadowsocks-libev  该如何配置呢？

**Comment by ohyeah521** [comment]
我config文件中  server 填写的 ssserver.com ，method 是rc4，密码写的是password，远程端口写的是80，然后启动ss，用chrome访问网站提示我下载一个文件，不知道是什么问题。
